#!/usr/bin/env python

import subprocess
import argparse
import sys


print('Enter text to find:')
match = raw_input()

def escape(s):
    return s.replace("\\", "\\\\").replace("/", "\\/")

fmatch = escape(match)

cmd = []
cmd.append('grep')
cmd.append('-H')
cmd.append('-r')
cmd.append(fmatch)

sys.exit(subprocess.call(cmd, shell=False))