#!/usr/bin/env python

import subprocess
import sys

print('Enter text to find:')
match = raw_input()
print('Enter text to replace:')
replace = raw_input()

def escape(s):
    return s.replace("\\", "\\\\").replace("/", "\\/")

fmatch = escape(match)
freplace = escape(replace)

findp = subprocess.Popen(['grep', '-rl', fmatch, '.'], stdout=subprocess.PIPE)
output = subprocess.check_output(['xargs', 'sed', '-i', 's/{}/{}/g'.format(fmatch, freplace)], stdin=findp.stdout)
findp.wait()
